#!/bin/sh
set -e

case "$1" in
      remove)
        rm -f /tmp/quick-secrets-0.0.1.gem
        gem uninstall -a -x quick-secrets
        rm -rf /etc/quick_secrets/*
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0

